kind: Service
apiVersion: v1
metadata:
  name: ovn-northd
  namespace: {{ .Values.namespace }}
  {{- with .Values.central.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.central.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: ovn-northd
      protocol: TCP
      port: 6643
      targetPort: 6643
  type: ClusterIP
  {{- if eq .Values.networking.stack "Dual" }}
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  selector:
    app.kubernetes.io/name: ovn-central
    app.kubernetes.io/part-of: kube-ovn
    ovn-northd-leader: "true"
  sessionAffinity: None
