{{- if .Values.validatingWebhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kube-ovn-webhook
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.namespace }}/kube-ovn-webhook-serving-cert
    {{- with .Values.validatingWebhook.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.validatingWebhook.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
webhooks:
  - name: pod-ip-validating.kube-ovn.io
    rules:
      - operations:
          - CREATE
        apiGroups:
          - "apps"
        apiVersions:
          - v1
        resources:
          - deployments
          - statefulsets
          - daemonsets
      - operations:
          - CREATE
        apiGroups:
          - "batch"
        apiVersions:
          - v1
        resources:
          - jobs
          - cronjobs
      - operations:
          - CREATE
        apiGroups:
          - ""
        apiVersions:
          - v1
        resources:
          - pods
      - operations:
          - CREATE
          - UPDATE
          - DELETE
        apiGroups:
          - "kubeovn.io"
        apiVersions:
          - v1
        resources:
          - subnets
          - vpcs
          - vips
          - vpc-nat-gateways
          - iptables-eips
          - iptables-dnat-rules
          - iptables-snat-rules
          - iptables-fip-rules
    failurePolicy: Ignore
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
    clientConfig:
      service:
        namespace: {{ .Values.namespace }}
        name: kube-ovn-webhook
        path: /validating
        port: 443
{{- end }}